dist: xenial
language: python
sudo: required
matrix:
  include:
    - name: Python 3.7, PG 10
      python: 3.7
      env: DATABASE=postgres
      addons:
        postgresql: 10
    - name: Python 3.8, PG 10
      python: 3.8
      env: DATABASE=postgres
      addons:
        postgresql: 10
services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database guillotina;' -U postgres

cache:
  directories:
    - eggs
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - flake8 guillotina_pgfield --config=setup.cfg
  - isort -c -rc guillotina_nats/
  - black --check --verbose guillotina_nats
  - pytest -rfE --reruns 2 --cov=guillotina_nats -s --tb=native -v --cov-report term-missing --cov-append guillotina_nats
after_success:
  - codecov

# safelist
branches:
  only:
  - master
