name: guillotina

on: [push]

jobs:

  # Job to run pre-checks
  pre-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install flake8==3.7.7
          pip install mypy==0.720
          pip install mypy-zope==0.2.0
          pip install black==19.10b0
          pip install isort==4.3.21
      - name: Run pre-checks
        run: |
          flake8 guillotina_nats --config=setup.cfg
          mypy guillotina_nats/ --ignore-missing-imports
          isort -c -rc guillotina_nats/
          black --check --verbose guillotina_nats
  # Job to run tests
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the package
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Run tests
        run: |
          pytest -rfE --reruns 2 --cov=guillotina_nats -s --tb=native -v --cov-report xml --cov-append guillotina_nats

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
